name: CI

on:
  push:
    branches:
      - SDL2
  pull_request:
    branches:
      - SDL2
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        zig-version: [0.15.0, 0.16.0, master]
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Zig 0.15.0 does not work with newer Xcode in latest macOS image.
        # https://codeberg.org/ziglang/zig/issues/31658
        include:
          - zig-version: 0.15.0
            os: macos-15
        exclude:
          - zig-version: 0.15.0
            os: macos-latest
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.zig-version == 'master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libgles-dev libpulse-dev libxext-dev

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Check Formatting
        run: zig fmt --ast-check --check .

      - name: Build
        run: zig build --summary all
